### PR TITLE
Updated tabbed

### PR DESCRIPTION
**Pull request by ghost**
Changed tab movement shorcuts to jump between words

### CODE REVIEW

**Comment by gryf** [comment]
Hi @maximhesed! Thanks for the contribution :)
Because I really like shift+arrows tab traverse, I would like to keep it like that. Maybe a configurable options to define a shourtcuts would be a better idea?

**Comment by ghost** [comment]
> Hi @maximhesed! Thanks for the contribution :)
> Because I really like shift+arrows tab traverse, I would like to keep it like that. Maybe a configurable options do define a shourtcuts would be a better idea?

Hm... may be so. Yes, exactly!
Your extension is really beautiful. ;)
But... I'm can't open the more tabs through some time...

**Review by gryf — CHANGES_REQUESTED** [review]
Please, provide a configuration option for defining keys used for traversing between the tabs.

**Comment by ghost** [comment]
No, i can't _create_ new tabs through some time. But, sometime i can do it and sometime i can't.
And it's not depends by tabbed extension... Hm...
Excuse me. I just want use your extension because it's really cool thing!.. 
But due some troubles i can't enjoy these. Check the issues.

**Comment by gryf** [comment]
Wait. You're saying, that you sometimes can't create tabs and sometimes can?

**Comment by ghost** [comment]
Yes, absolute exactly. Now, I check your last commit and repeat this action...

EDIT: no, still the bug remaining. May be it's only just me have this problem...

**Comment by gryf** [comment]
It is unrelated to this PR, could you fill the bug, and provide the steps to reproduce it?

**Comment by ghost** [comment]
Here is my ~/.Xdefaults:

```
URxvt.termName: rxvt-unicode
URxvt.scrollBar: false

URxvt.background: #000000
URxvt.foreground: #FFFFFF

URxvt.font: xft:DejaVu Sans Mono:pixelsize=13
URxvt.boldFont: xft:DejaVu Sans Mono:pixelsize=13
URxvt.letterSpace: -1

URxvt.saveLines: 1000000

URxvt.perl-ext-common: default,matcher,vtwheel
URxvt.perl-ext: tabbed
URxvt.perl-lib: /home/ksyrx/.urxvt/

URxvt.UrlLauncher: /usr/bin/chromium
URxvt.matcher.button: C1

URxvt.keysym.Control-0x2b: perl:font-size:increase
URxvt.keysym.Control-0x2d: perl:font-size:decrease

URxvt.keysym.Home:          \033[1~
URxvt.keysym.End:           \033[4~
URxvt.keysym.Control-Up:    \033[1;5A
URxvt.keysym.Control-Down:  \033[1;5B
URxvt.keysym.Control-Left:  \033[1;5D
URxvt.keysym.Control-Right: \033[1;5C

URxvt.color0: #000000
URxvt.color1: #B21818
URxvt.color2: #18B218
URxvt.color3: #B26818
URxvt.color4: #1818B2
URxvt.color5: #B218B2
URxvt.color6: #18B2B2
URxvt.color7: #B2B2B2
URxvt.color8: #686868
URxvt.color9: #FF5454
URxvt.color10: #54FF54
URxvt.color11: #FFFF54
URxvt.color12: #5454FF
URxvt.color13: #FF54FF
URxvt.color14: #54FFFF
URxvt.color15: #FFFFFF

! Tabbed extension configuration
URxvt.tabbed.tabbar-fg: 8
URxvt.tabbed.tabbar-bg: 0
URxvt.tabbed.tab-fg: 15
URxvt.tabbed.tab-bg: 8
URxvt.tabbed.new-button: false

! Transparency
URxvt.transparent: true
URxvt.shading: 50

! Disable bell
URxvt.insecure: false

URxvt.iso14755: false
```
I run urxvt and press ctrl+shift+N but nothing. If I open new urxvt, then I can create 5-6 tabs there.

**Comment by gryf** [comment]
I've created an issue #4 on that subject. As for this PR, I still rather have this shortcut configured, instead of hardcoded :)

**Comment by ghost** [comment]
Oh WOW!!! 

Sorry me, please. It's fake problem. I solved it. 
Just need to reduce `URxvt.saveLines` (i changed to 30000). 
There was one million... 
Oh damn.

So, i can create more than 15 TABS!!!

Your extension really amazing, just i fool...

Excuse me.

**Comment by gryf** [comment]
No worries :)

**Pull request closed without merging**
